# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8003b96f32cf4112c17e5b7720d78a39105c41bcf938c36b12f6c893849d46d79392e4ec30fdc42296212b190ed2366b448c6414da0fbe86650243836651a62b

test:
  secret_key_base: 458c2f8af2e1757e0d326f73225c2535ea583d9431dd75e6a512d4b5c2fdd7bd3c891ea60893fb40dee64e95c23ee36c2f8b699d42d9395905cd7bda46dbd483

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
